import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const catalogSource=readFileSync('src/workspace-engine/widgetCatalog.ts','utf8');
const registrationSource=readFileSync('src/workspace-engine/registerBuiltinWidgets.ts','utf8');
const visibleCatalogSource=catalogSource.slice(catalogSource.indexOf('const allWorkspaceWidgetCatalog'),catalogSource.indexOf('// Compatibilidade interna'));
const catalogEntries=Array.from(visibleCatalogSource.matchAll(/\{type:'([^']+)'[\s\S]*?readiness:'(ready|configurable|planned)'/g)).map(match=>({type:match[1],readiness:match[2]}));
const registeredTypes=Array.from(registrationSource.matchAll(/registerWorkspaceWidgetRenderer\('([^']+)'/g)).map(match=>match[1]);
const registered=new Set(registeredTypes);
test('biblioteca oficial mantém 19 tipos únicos e maturidade explícita',()=>{assert.equal(catalogEntries.length,19);assert.equal(new Set(catalogEntries.map(item=>item.type)).size,19);});
test('todos os 19 widgets oficiais possuem renderer builtin na baseline 1.0',()=>{assert.equal(registered.size,19);assert.deepEqual(catalogEntries.filter(item=>!registered.has(item.type)).map(item=>item.type),[]);});
test('nenhum widget permanece planejado sem implementação na baseline 1.0',()=>{assert.deepEqual(catalogEntries.filter(item=>item.readiness==='planned'),[]);});
