import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { workspaceRegistry } from '../src/workspace-engine/registry';
import { createOfficialWorkspaceDefinition, OFFICIAL_WORKSPACE_TEMPLATES } from '../src/workspace-engine/workspaceOfficialFactory';

test('official reception and governance instances are generated by the Workspace Factory', () => {
  assert.deepEqual(
    workspaceRegistry,
    OFFICIAL_WORKSPACE_TEMPLATES.map(template => createOfficialWorkspaceDefinition(template.id)),
  );
  assert.deepEqual(workspaceRegistry.map(item => item.id), ['workspace-governanca', 'workspace-recepcao']);
});

test('factory cutover preserves historical base ids and widget ids', () => {
  const governance = createOfficialWorkspaceDefinition('workspace-governanca');
  const reception = createOfficialWorkspaceDefinition('workspace-recepcao');

  assert.equal(governance.widgets.some(widget => widget.id === 'governanca-kanban'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-reservas'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-calendario-ocupacao'), true);
  assert.equal(reception.widgets.some(widget => widget.id === 'recepcao-kanban'), true);
});

test('registry no longer declares official Workspace objects by hand', () => {
  const source = readFileSync(new URL('../src/workspace-engine/registry.ts', import.meta.url), 'utf8');
  assert.match(source, /createOfficialWorkspaceDefinitions\(\)/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-governanca['"]/);
  assert.doesNotMatch(source, /id:\s*['"]workspace-recepcao['"]/);
  assert.doesNotMatch(source, /widgets:\s*normalizeWorkspaceWidgets/);
});
