-- Hotel OS: additive operational contract for PDV/KDS.
-- This migration intentionally does not alter or drop legacy tables/policies.

create extension if not exists pgcrypto;

create table if not exists public.pdv_produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  categoria text not null default 'Geral',
  preco numeric(12,2) not null check (preco >= 0),
  estoque_atual numeric(12,3) not null default 0 check (estoque_atual >= 0),
  estoque_minimo numeric(12,3) not null default 0 check (estoque_minimo >= 0),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pdv_pedidos (
  id uuid primary key default gen_random_uuid(),
  hotel_id text,
  numero bigint generated by default as identity unique,
  origem text not null check (origem in ('balcao','quarto','tablet')),
  quarto_id text,
  status text not null default 'novo' check (status in ('novo','em_preparo','pronto','entregue','cancelado','fechado')),
  total numeric(12,2) not null default 0 check (total >= 0),
  idempotency_key text not null unique,
  criado_por text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pdv_pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pdv_pedidos(id) on delete cascade,
  produto_id uuid not null references public.pdv_produtos(id),
  quantidade numeric(12,3) not null check (quantidade > 0),
  preco_unitario numeric(12,2) not null check (preco_unitario >= 0),
  subtotal numeric(12,2) generated always as (round(quantidade * preco_unitario, 2)) stored,
  observacao text
);

create table if not exists public.kds_fila (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null unique references public.pdv_pedidos(id) on delete cascade,
  status text not null default 'novo' check (status in ('novo','em_preparo','pronto','entregue','cancelado')),
  recebido_em timestamptz not null default now(),
  iniciado_em timestamptz,
  pronto_em timestamptz,
  entregue_em timestamptz,
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_pdv_pedidos_status on public.pdv_pedidos(status);
create index if not exists idx_pdv_pedidos_hotel on public.pdv_pedidos(hotel_id);
create index if not exists idx_pdv_itens_pedido on public.pdv_pedido_itens(pedido_id);
create index if not exists idx_kds_status on public.kds_fila(status);

create or replace function public.criar_pedido_pdv(
  p_hotel_id text,
  p_origem text,
  p_quarto_id text,
  p_idempotency_key text,
  p_itens jsonb,
  p_criado_por text default auth.uid()::text
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_pedido_id uuid;
  v_item jsonb;
  v_produto public.pdv_produtos%rowtype;
  v_total numeric(12,2) := 0;
  v_quantidade numeric(12,3);
begin
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
    raise exception 'O pedido precisa possuir pelo menos um item';
  end if;

  select id into v_pedido_id from public.pdv_pedidos where idempotency_key = p_idempotency_key;
  if v_pedido_id is not null then return v_pedido_id; end if;

  if p_origem not in ('balcao','quarto','tablet') then raise exception 'Origem de pedido inválida'; end if;
  if p_origem = 'quarto' and nullif(trim(p_quarto_id), '') is null then raise exception 'Quarto obrigatório para Room Service'; end if;

  insert into public.pdv_pedidos (hotel_id, origem, quarto_id, idempotency_key, criado_por)
  values (p_hotel_id, p_origem, nullif(p_quarto_id, ''), p_idempotency_key, p_criado_por)
  returning id into v_pedido_id;

  for v_item in select * from jsonb_array_elements(p_itens) loop
    select * into v_produto
    from public.pdv_produtos
    where id = (v_item->>'produto_id')::uuid and ativo = true
    for update;

    if not found then raise exception 'Produto não encontrado ou inativo: %', v_item->>'produto_id'; end if;
    v_quantidade := (v_item->>'quantidade')::numeric;
    if v_quantidade is null or v_quantidade <= 0 then raise exception 'Quantidade inválida para o produto %', v_produto.nome; end if;
    if v_produto.estoque_atual < v_quantidade then raise exception 'Estoque insuficiente para %', v_produto.nome; end if;

    insert into public.pdv_pedido_itens (pedido_id, produto_id, quantidade, preco_unitario, observacao)
    values (v_pedido_id, v_produto.id, v_quantidade, v_produto.preco, v_item->>'observacao');

    update public.pdv_produtos set estoque_atual = estoque_atual - v_quantidade, atualizado_em = now() where id = v_produto.id;
    v_total := v_total + round(v_produto.preco * v_quantidade, 2);
  end loop;

  update public.pdv_pedidos set total = v_total, atualizado_em = now() where id = v_pedido_id;
  insert into public.kds_fila (pedido_id) values (v_pedido_id);
  return v_pedido_id;
exception when unique_violation then
  select id into v_pedido_id from public.pdv_pedidos where idempotency_key = p_idempotency_key;
  if v_pedido_id is not null then return v_pedido_id; end if;
  raise;
end;
$$;

create or replace function public.atualizar_status_kds(p_pedido_id uuid, p_status text)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_status not in ('novo','em_preparo','pronto','entregue','cancelado') then raise exception 'Status KDS inválido'; end if;
  update public.kds_fila
  set status = p_status,
      iniciado_em = case when p_status = 'em_preparo' and iniciado_em is null then now() else iniciado_em end,
      pronto_em = case when p_status = 'pronto' and pronto_em is null then now() else pronto_em end,
      entregue_em = case when p_status = 'entregue' and entregue_em is null then now() else entregue_em end,
      atualizado_em = now()
  where pedido_id = p_pedido_id;
  update public.pdv_pedidos set status = p_status, atualizado_em = now() where id = p_pedido_id;
end;
$$;

alter table public.pdv_produtos enable row level security;
alter table public.pdv_pedidos enable row level security;
alter table public.pdv_pedido_itens enable row level security;
alter table public.kds_fila enable row level security;

-- Tenant-specific RLS policies must be installed after the project's canonical hotel/role membership contract is finalized.

do $$ begin alter publication supabase_realtime add table public.pdv_pedidos; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.kds_fila; exception when duplicate_object then null; end $$;
