import { registerWorkspaceWidgetRenderer } from './widgetRuntimeRegistry';
import { TaskKanbanWidget } from './widgets/TaskKanbanWidget';
import { ReceptionRoomMapWidget } from './widgets/ReceptionRoomMapWidget';
import { RoomDetailsWidget } from './widgets/RoomDetailsWidget';
import { QuickActionsWidget } from './widgets/QuickActionsWidget';
import { MaintenanceWidget } from './widgets/MaintenanceWidget';
import { TeamWidget } from './widgets/TeamWidget';
import { UserAccessWidget } from './widgets/UserAccessWidget';
import { AutomationAdminWidget } from './widgets/AutomationAdminWidget';
import { ArrivalsWidget, DeparturesWidget, ReceptionAlertsWidget, ReceptionSummaryWidget } from './widgets/ReceptionInfoWidgets';
import { ActiveStaysWidget, GuestsWidget } from './widgets/ReceptionGuestStayWidgets';
import { ReservationsWidget } from './widgets/ReservationsWidget';
import { OccupancyCalendarWidget } from './widgets/OccupancyCalendarWidget';
import { DashboardWidget } from './widgets/DashboardWidget';
import { StayFinanceWidget } from './widgets/StayFinanceWidget';
import { FrigobarWidget } from './widgets/FrigobarWidget';

let registered = false;

export const registerBuiltinWorkspaceWidgets = () => {
  if (registered) return;
  registered = true;
  registerWorkspaceWidgetRenderer('dashboard', DashboardWidget);
  registerWorkspaceWidgetRenderer('stay-finance', StayFinanceWidget);
  registerWorkspaceWidgetRenderer('frigobar', FrigobarWidget);
  registerWorkspaceWidgetRenderer('task-kanban', TaskKanbanWidget);
  registerWorkspaceWidgetRenderer('room-map', ReceptionRoomMapWidget);
  registerWorkspaceWidgetRenderer('room-details', RoomDetailsWidget);
  registerWorkspaceWidgetRenderer('quick-actions', QuickActionsWidget);
  registerWorkspaceWidgetRenderer('maintenance', MaintenanceWidget);
  registerWorkspaceWidgetRenderer('team', TeamWidget);
  registerWorkspaceWidgetRenderer('user-access', UserAccessWidget);
  registerWorkspaceWidgetRenderer('automation-admin', AutomationAdminWidget);
  registerWorkspaceWidgetRenderer('guests', GuestsWidget);
  registerWorkspaceWidgetRenderer('reservations-list', ReservationsWidget);
  registerWorkspaceWidgetRenderer('occupancy-calendar', OccupancyCalendarWidget);
  registerWorkspaceWidgetRenderer('active-stays', ActiveStaysWidget);
  registerWorkspaceWidgetRenderer('arrivals', ArrivalsWidget);
  registerWorkspaceWidgetRenderer('departures', DeparturesWidget);
  registerWorkspaceWidgetRenderer('alerts', ReceptionAlertsWidget);
  registerWorkspaceWidgetRenderer('metrics', ReceptionSummaryWidget);
};
