import { OperationalSectorId } from '../domain/operationalSectors';
import { WorkspaceDefinition } from './types';
import { DEFAULT_WORKSPACE_HOTEL_ID, loadWorkspaceOverrides, mergeWorkspaceDefinition } from './workspaceConfigStore';
import { migrateWorkspaceDefinitionToCanonicalWidgets } from './workspaceMigration';
import { createOfficialWorkspaceDefinitions } from './workspaceOfficialFactory';

/**
 * Compatibility/runtime registry only. Official Workspace instances are
 * generated by the Workspace Factory and merely exposed here for consumers
 * that still resolve definitions through the historical registry API.
 */
export const workspaceRegistry: WorkspaceDefinition[] = createOfficialWorkspaceDefinitions();

const canonicalForRuntime = (definition: WorkspaceDefinition) =>
  definition.sectors.includes('recepcao')
    ? migrateWorkspaceDefinitionToCanonicalWidgets(definition).definition
    : definition;

export const getAllWorkspaceDefinitions = (hotelId = DEFAULT_WORKSPACE_HOTEL_ID): WorkspaceDefinition[] => {
  const overrides = loadWorkspaceOverrides(hotelId);
  const baseIds = new Set(workspaceRegistry.map(workspace => workspace.id));
  const custom = Object.values(overrides)
    .filter(workspace => !baseIds.has(workspace.id))
    .map(canonicalForRuntime);
  const bases = workspaceRegistry.map(base => canonicalForRuntime(mergeWorkspaceDefinition(base, hotelId)));
  return [...custom, ...bases];
};

export const getWorkspaceDefinition = (workspaceId: string, hotelId = DEFAULT_WORKSPACE_HOTEL_ID) =>
  getAllWorkspaceDefinitions(hotelId).find(workspace => workspace.id === workspaceId) || null;

/** Áreas sem associação continuam públicas por compatibilidade; quando há IDs,
 * somente usuários associados (ou uma camada RBAC administrativa acima) as vêem. */
export const getWorkspacesForUser = (userId: string | undefined, hotelId = DEFAULT_WORKSPACE_HOTEL_ID) =>
  getAllWorkspaceDefinitions(hotelId).filter(workspace => {
    const assigned = workspace.assignedUserIds || [];
    return assigned.length === 0 || (!!userId && assigned.includes(userId));
  });

/**
 * Resolve o Workspace operacional do usuário preservando a Fábrica como fonte
 * de verdade. Entre áreas do mesmo setor, a associação explícita feita na
 * Fábrica sempre vence. Apenas quando não existe associação explícita usamos
 * uma área pública/compartilhada do setor como fallback de compatibilidade.
 */
export const resolveWorkspaceForUserAndSectors = (
  userId: string | undefined,
  sectorIds: OperationalSectorId[],
  hotelId = DEFAULT_WORKSPACE_HOTEL_ID,
) => {
  const candidates = getAllWorkspaceDefinitions(hotelId)
    .filter(workspace => workspace.sectors.some(sector => sectorIds.includes(sector)));

  if (userId) {
    const assigned = candidates.find(workspace => (workspace.assignedUserIds || []).includes(userId));
    if (assigned) return assigned;
  }

  return candidates.find(workspace => (workspace.assignedUserIds || []).length === 0) || null;
};

/** API histórica mantida para consumidores que ainda não possuem contexto de usuário. */
export const resolveWorkspaceForSectors = (sectorIds: OperationalSectorId[], hotelId = DEFAULT_WORKSPACE_HOTEL_ID) =>
  getAllWorkspaceDefinitions(hotelId).find(workspace => workspace.sectors.some(sector => sectorIds.includes(sector))) || null;
