import { OperationalSectorId } from '../domain/operationalSectors';
import { legacySpanToWidth, normalizeWidgetPresentation } from './presentation';
import { WorkspaceWidgetDefinition, WorkspaceWidgetType } from './types';

export type WorkspaceWidgetReadiness = 'ready' | 'configurable' | 'planned';
export type WorkspaceWidgetKdsSuitability = 'supported' | 'limited' | 'unsupported';
export interface WorkspaceWidgetCatalogItem { type: WorkspaceWidgetType; label: string; description: string; category: 'operacao'|'dados'|'equipe'|'atalhos'; requiresBoard:boolean; defaultSpan:WorkspaceWidgetDefinition['span']; defaultDataSource?:WorkspaceWidgetDefinition['dataSource']; sectors?:OperationalSectorId[]; readiness:WorkspaceWidgetReadiness; readinessNote?:string; legacy?:boolean; }
const allSectors:OperationalSectorId[]=['operacao','governanca','recepcao','manutencao','cozinha'];
const allWorkspaceWidgetCatalog:WorkspaceWidgetCatalogItem[]=[
{type:'metrics',label:'Indicadores',description:'Resumo de volumes e estados do fluxo operacional.',category:'operacao',requiresBoard:false,defaultSpan:'full',defaultDataSource:'composite',sectors:allSectors,readiness:'ready'},
{type:'dashboard',label:'Dashboard',description:'Dashboard personalizado composto por métricas e visualizações do Dashboard Engine.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'dashboard',sectors:allSectors,readiness:'ready'},
{type:'stay-finance',label:'Financeiro da hospedagem',description:'Folio oficial da hospedagem.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'finance',sectors:['recepcao'],readiness:'ready'},
{type:'frigobar',label:'Frigobar',description:'Consumo e reposição via Frigobar Core.',category:'operacao',requiresBoard:false,defaultSpan:'full',defaultDataSource:'frigobar',sectors:['operacao','recepcao','governanca'],readiness:'ready'},
{type:'task-kanban',label:'Kanban de tarefas',description:'Quadro operacional vinculado ao motor Kanban.',category:'operacao',requiresBoard:true,defaultSpan:'full',defaultDataSource:'kanban',sectors:allSectors,readiness:'ready'},
{type:'room-map',label:'Mapa de quartos',description:'Situação operacional dos quartos.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'composite',sectors:['recepcao','governanca','manutencao'],readiness:'configurable'},
{type:'room-details',label:'Detalhes do quarto',description:'Contexto do quarto, hóspede e reserva.',category:'dados',requiresBoard:false,defaultSpan:2,defaultDataSource:'composite',sectors:['recepcao','governanca','manutencao'],readiness:'configurable'},
{type:'guests',label:'Hóspedes',description:'Cadastro e busca de hóspedes.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'guests',sectors:['recepcao'],readiness:'ready'},
{type:'arrivals',label:'Chegadas',description:'Chegadas previstas e check-in.',category:'dados',requiresBoard:false,defaultSpan:2,defaultDataSource:'reservations',sectors:['recepcao'],readiness:'configurable'},
{type:'departures',label:'Saídas',description:'Saídas previstas e checkout.',category:'dados',requiresBoard:false,defaultSpan:2,defaultDataSource:'reservations',sectors:['recepcao'],readiness:'configurable'},
{type:'alerts',label:'Alertas',description:'Pendências do contexto operacional.',category:'operacao',requiresBoard:false,defaultSpan:2,defaultDataSource:'composite',sectors:allSectors,readiness:'ready'},
{type:'quick-actions',label:'Ações rápidas',description:'Ações contextuais do setor.',category:'atalhos',requiresBoard:false,defaultSpan:2,defaultDataSource:'composite',sectors:allSectors,readiness:'configurable'},
{type:'reservations-list',label:'Reservas',description:'Cria e acompanha reservas.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'reservations',sectors:['recepcao'],readiness:'ready'},
{type:'occupancy-calendar',label:'Calendário de ocupação',description:'Grade de ocupação por quarto e data.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'composite',sectors:['recepcao'],readiness:'ready'},
{type:'active-stays',label:'Hóspedes hospedados',description:'Hospedagens ativas.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'composite',sectors:['recepcao'],readiness:'ready'},
{type:'maintenance',label:'Manutenção',description:'Ordens técnicas sobre o Kanban oficial.',category:'operacao',requiresBoard:false,defaultSpan:2,defaultDataSource:'maintenance',sectors:['manutencao','governanca','recepcao'],readiness:'configurable'},
{type:'orders',label:'Pedidos',description:'Fila operacional do KDS existente.',category:'operacao',requiresBoard:false,defaultSpan:'full',defaultDataSource:'orders',sectors:['cozinha','recepcao'],readiness:'ready',readinessNote:'Reutiliza pdvService e KDS em tempo real; não cria motor de pedidos paralelo.'},
{type:'team',label:'Equipe',description:'Pessoas ativas vinculadas aos setores operacionais.',category:'equipe',requiresBoard:false,defaultSpan:2,defaultDataSource:'users',sectors:allSectors,readiness:'ready'},
{type:'shortcuts',label:'Atalhos',description:'Links configurados no próprio Workspace.',category:'atalhos',requiresBoard:false,defaultSpan:2,defaultDataSource:'composite',sectors:allSectors,readiness:'configurable'},
// Compatibilidade interna
{type:'kanban-cards',label:'Kanban (legado)',description:'Compatibilidade.',category:'operacao',requiresBoard:true,defaultSpan:'full',defaultDataSource:'kanban',sectors:allSectors,readiness:'ready',legacy:true},
{type:'rooms-list',label:'Quartos (legado)',description:'Compatibilidade.',category:'dados',requiresBoard:false,defaultSpan:'full',defaultDataSource:'composite',sectors:['recepcao','governanca','manutencao'],readiness:'configurable',legacy:true},
{type:'checkins',label:'Chegadas e saídas (legado)',description:'Compatibilidade.',category:'dados',requiresBoard:false,defaultSpan:2,defaultDataSource:'reservations',sectors:['recepcao'],readiness:'configurable',legacy:true},
];
export const workspaceWidgetCatalog=allWorkspaceWidgetCatalog.filter(item=>!item.legacy);
export const getWidgetCatalogItem=(type:WorkspaceWidgetType)=>allWorkspaceWidgetCatalog.find(item=>item.type===type)||null;
export const getWidgetAvailability=(type:WorkspaceWidgetType,sector:OperationalSectorId)=>{const item=getWidgetCatalogItem(type);if(!item)return{allowed:false,readiness:'planned' as const,reason:'Widget não registrado na biblioteca.'};const allowed=!item.sectors?.length||item.sectors.includes(sector);if(!allowed)return{allowed:false,readiness:item.readiness,reason:`Não disponível para o setor ${sector}.`};if(item.readiness==='planned')return{allowed:false,readiness:item.readiness,reason:item.readinessNote||'Widget ainda não possui renderer operacional consolidado.'};return{allowed:true,readiness:item.readiness,reason:item.readinessNote||''};};
const kdsSuitability:Partial<Record<WorkspaceWidgetType,{suitability:WorkspaceWidgetKdsSuitability;reason:string}>>={'stay-finance':{suitability:'limited',reason:'Fluxo financeiro exige interação próxima.'},frigobar:{suitability:'limited',reason:'Operação exige interação.'},'room-details':{suitability:'limited',reason:'Painel contextual.'},guests:{suitability:'limited',reason:'Cadastro não é ideal a distância.'},'reservations-list':{suitability:'limited',reason:'Edição exige interação.'},'quick-actions':{suitability:'unsupported',reason:'Exige interação direta.'},shortcuts:{suitability:'unsupported',reason:'Exige navegação interativa.'},team:{suitability:'limited',reason:'Adequado apenas como referência visual.'}};
export const getWidgetKdsSuitability=(type:WorkspaceWidgetType)=>kdsSuitability[type]||{suitability:'supported' as const,reason:''};
export const createWorkspaceWidget=(type:WorkspaceWidgetType,options?:{boardId?:string;order?:number}):WorkspaceWidgetDefinition=>{const item=getWidgetCatalogItem(type);if(item?.legacy)throw new Error(`Widget legado ${type} não pode ser criado pela Fábrica.`);const suffix=Math.random().toString(36).slice(2,8);const span=item?.defaultSpan??'full';return{id:`widget-${type}-${Date.now().toString(36)}-${suffix}`,type,title:item?.label||type,boardId:item?.requiresBoard?options?.boardId:undefined,order:options?.order??10,span,enabled:true,dataSource:item?.defaultDataSource,filters:{},actions:{},permissions:{view:true},presentation:{display:span==='button'?'button':'panel',width:legacySpanToWidth(span),height:'auto',visual:'standard',header:'full'},settings:{}};};
export const normalizeWorkspaceWidgets=(widgets:WorkspaceWidgetDefinition[])=>widgets.map((widget,index)=>{const catalog=getWidgetCatalogItem(widget.type);return{...widget,order:widget.order??index,span:widget.span??catalog?.defaultSpan??'full',enabled:widget.enabled!==false,dataSource:widget.dataSource??catalog?.defaultDataSource,filters:widget.filters??{},actions:widget.actions??{},permissions:widget.permissions??{view:true},presentation:normalizeWidgetPresentation(widget,catalog?.defaultSpan),settings:widget.settings??{}};}).sort((a,b)=>(a.order??0)-(b.order??0));
export const canonicalWidgetType=(type:WorkspaceWidgetType):WorkspaceWidgetType=>type==='kanban-cards'?'task-kanban':type==='rooms-list'?'room-map':type;
