export const PERMISSIONS = {
  reservationsView: 'reservations.view',
  reservationsCreate: 'reservations.create',
  reservationsEdit: 'reservations.edit',
  reservationsCancel: 'reservations.cancel',
  reservationsCheckin: 'reservations.checkin',
  reservationsCheckout: 'reservations.checkout',
  posView: 'pos.view',
  posCreateOrder: 'pos.create_order',
  posEditOrder: 'pos.edit_order',
  posCancelItem: 'pos.cancel_item',
  posApplyDiscount: 'pos.apply_discount',
  posOpenCash: 'pos.open_cash',
  posCloseCash: 'pos.close_cash',
  posRefund: 'pos.refund',
  housekeepingView: 'housekeeping.view',
  housekeepingAssign: 'housekeeping.assign',
  housekeepingStart: 'housekeeping.start',
  housekeepingComplete: 'housekeeping.complete',
  maintenanceView: 'maintenance.view',
  maintenanceCreate: 'maintenance.create',
  maintenanceAssign: 'maintenance.assign',
  maintenanceComplete: 'maintenance.complete',
  financeView: 'finance.view',
  financeCreatePayment: 'finance.create_payment',
  financeRefund: 'finance.refund',
  financeCloseCash: 'finance.close_cash',
  tabletMenuView: 'tablet.menu.view',
  tabletOrderCreate: 'tablet.order.create',
  tabletOrderView: 'tablet.order.view',
  tabletServiceRequest: 'tablet.service.request',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];
