-- Reception room ↔ reservation ↔ guest binding.
-- The reception room card is a fixed projection of the room. Reservation changes
-- attach/detach the guest without replacing the card, and room transfers preserve history.

create table if not exists public.reservation_room_history (
  id bigint generated by default as identity primary key,
  reservation_id text not null references public.reservas(id) on delete cascade,
  guest_id text references public.hospedes(id) on delete set null,
  from_room_id text references public.quartos(id) on delete set null,
  to_room_id text references public.quartos(id) on delete set null,
  event_type text not null check (event_type in ('reservation_assigned','checkin','room_transfer','checkout')),
  actor_user_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_reservation_room_history_reservation
  on public.reservation_room_history (reservation_id, created_at desc);
create index if not exists idx_reservation_room_history_rooms
  on public.reservation_room_history (from_room_id, to_room_id, created_at desc);

alter table public.reservation_room_history enable row level security;

drop policy if exists reservation_room_history_select on public.reservation_room_history;
create policy reservation_room_history_select on public.reservation_room_history
for select to anon, authenticated using (true);

drop policy if exists reservation_room_history_insert on public.reservation_room_history;
create policy reservation_room_history_insert on public.reservation_room_history
for insert to anon, authenticated with check (true);

grant select, insert on public.reservation_room_history to anon, authenticated;
grant usage, select on sequence public.reservation_room_history_id_seq to anon, authenticated;

create or replace function public.refresh_reception_room_guest_binding(p_room_id text)
returns void
language plpgsql
set search_path = public
as $$
declare
  v_reservation public.reservas%rowtype;
  v_guest public.hospedes%rowtype;
  v_metadata jsonb;
begin
  if p_room_id is null or btrim(p_room_id) = '' then return; end if;

  select r.* into v_reservation
    from public.reservas r
   where r.quarto_id::text = p_room_id::text
     and r.status in ('checkin_realizado', 'confirmada', 'pendente')
   order by
     case r.status when 'checkin_realizado' then 0 when 'confirmada' then 1 else 2 end,
     case when r.checkin >= current_date then 0 else 1 end,
     r.checkin asc,
     r.created_at asc nulls last
   limit 1;

  if found then
    select h.* into v_guest from public.hospedes h where h.id::text = v_reservation.hospede_id::text limit 1;

    v_metadata := jsonb_strip_nulls(jsonb_build_object(
      'guest_binding', true,
      'reservation_id', v_reservation.id,
      'reservation_code', v_reservation.codigo,
      'reservation_status', v_reservation.status,
      'reservation_checkin', v_reservation.checkin,
      'reservation_checkout', v_reservation.checkout,
      'guest_id', v_reservation.hospede_id,
      'guest_name', v_guest.nome
    ));

    update public.kanban_cards c
       set reservation_id = v_reservation.id,
           guest_name = v_guest.nome,
           metadata = (coalesce(c.metadata, '{}'::jsonb) - array[
             'guest_binding','reservation_id','reservation_code','reservation_status',
             'reservation_checkin','reservation_checkout','guest_id','guest_name'
           ]) || v_metadata,
           updated_at = now()
     where c.id = 'room-rec-' || p_room_id::text
       and c.board_id = 'kanban-board-recepcao-quartos';
  else
    update public.kanban_cards c
       set reservation_id = null,
           guest_name = null,
           metadata = coalesce(c.metadata, '{}'::jsonb) - array[
             'guest_binding','reservation_id','reservation_code','reservation_status',
             'reservation_checkin','reservation_checkout','guest_id','guest_name'
           ],
           updated_at = now()
     where c.id = 'room-rec-' || p_room_id::text
       and c.board_id = 'kanban-board-recepcao-quartos';
  end if;
end;
$$;

create or replace function public.trg_sync_reception_guest_binding_from_reservation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if new.quarto_id is not null then
      insert into public.reservation_room_history (
        reservation_id, guest_id, from_room_id, to_room_id, event_type, metadata
      ) values (
        new.id, new.hospede_id, null, new.quarto_id, 'reservation_assigned',
        jsonb_build_object('reservation_status', new.status, 'source', 'reservation')
      );
      perform public.refresh_reception_room_guest_binding(new.quarto_id::text);
    end if;
    return new;
  end if;

  if old.quarto_id is distinct from new.quarto_id then
    insert into public.reservation_room_history (
      reservation_id, guest_id, from_room_id, to_room_id, event_type, metadata
    ) values (
      new.id, new.hospede_id, old.quarto_id, new.quarto_id, 'room_transfer',
      jsonb_build_object('reservation_status', new.status, 'source', 'reservation')
    );
  elsif old.status is distinct from new.status and new.status = 'checkin_realizado' then
    insert into public.reservation_room_history (
      reservation_id, guest_id, from_room_id, to_room_id, event_type, metadata
    ) values (
      new.id, new.hospede_id, new.quarto_id, new.quarto_id, 'checkin',
      jsonb_build_object('from_status', old.status, 'to_status', new.status)
    );
  elsif old.status is distinct from new.status and new.status = 'checkout_concluido' then
    insert into public.reservation_room_history (
      reservation_id, guest_id, from_room_id, to_room_id, event_type, metadata
    ) values (
      new.id, new.hospede_id, new.quarto_id, null, 'checkout',
      jsonb_build_object('from_status', old.status, 'to_status', new.status)
    );
  end if;

  if old.quarto_id is not null then perform public.refresh_reception_room_guest_binding(old.quarto_id::text); end if;
  if new.quarto_id is not null and new.quarto_id is distinct from old.quarto_id then
    perform public.refresh_reception_room_guest_binding(new.quarto_id::text);
  elsif new.quarto_id is not null then
    perform public.refresh_reception_room_guest_binding(new.quarto_id::text);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_reception_guest_binding_from_reservation on public.reservas;
create trigger trg_sync_reception_guest_binding_from_reservation
after insert or update of quarto_id, hospede_id, status, checkin, checkout
on public.reservas
for each row execute function public.trg_sync_reception_guest_binding_from_reservation();

create or replace function public.reception_room_checkin(
  p_reservation_id text,
  p_actor_user_id text default null
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_reservation public.reservas%rowtype;
  v_room public.quartos%rowtype;
begin
  select * into v_reservation from public.reservas where id::text = p_reservation_id::text for update;
  if not found then raise exception 'Reserva não encontrada.'; end if;
  if v_reservation.quarto_id is null then raise exception 'A reserva não possui quarto vinculado.'; end if;
  if v_reservation.status not in ('confirmada','pendente') then raise exception 'A reserva não está disponível para check-in.'; end if;

  select * into v_room from public.quartos where id::text = v_reservation.quarto_id::text for update;
  if not found then raise exception 'Quarto da reserva não encontrado.'; end if;
  if exists (
    select 1 from public.reservas r
     where r.quarto_id::text = v_room.id::text
       and r.id::text <> v_reservation.id::text
       and r.status = 'checkin_realizado'
  ) then raise exception 'Já existe hóspede em check-in neste quarto.'; end if;
  if public.normalize_room_operational_status(coalesce(v_room.status_operacional, v_room.status)) <> 'disponivel'
     or coalesce(v_room.control_owner, 'recepcao') <> 'recepcao' then
    raise exception 'O quarto precisa estar disponível e sob controle da recepção.';
  end if;

  update public.reservas
     set status = 'checkin_realizado', checkin_horario = now()::text
   where id::text = v_reservation.id::text;

  update public.quartos
     set status = 'ocupado', status_operacional = 'ocupado', control_owner = 'recepcao',
         active_activity = null, updated_at = now()
   where id::text = v_room.id::text;

  update public.reservation_room_history
     set actor_user_id = p_actor_user_id
   where id = (select max(id) from public.reservation_room_history where reservation_id = v_reservation.id and event_type = 'checkin');

  return jsonb_build_object('ok', true, 'reservation_id', v_reservation.id, 'room_id', v_room.id, 'status', 'checkin_realizado');
end;
$$;

create or replace function public.reception_room_checkout(
  p_reservation_id text,
  p_actor_user_id text default null
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_reservation public.reservas%rowtype;
  v_room public.quartos%rowtype;
begin
  select * into v_reservation from public.reservas where id::text = p_reservation_id::text for update;
  if not found then raise exception 'Reserva não encontrada.'; end if;
  if v_reservation.status <> 'checkin_realizado' then raise exception 'Somente uma hospedagem ativa pode fazer check-out.'; end if;
  if v_reservation.quarto_id is null then raise exception 'A hospedagem não possui quarto vinculado.'; end if;

  select * into v_room from public.quartos where id::text = v_reservation.quarto_id::text for update;
  if not found then raise exception 'Quarto da hospedagem não encontrado.'; end if;

  update public.reservas
     set status = 'checkout_concluido', checkout_horario = now()::text
   where id::text = v_reservation.id::text;

  -- Checkout detaches the guest from Reception and hands the room to Governança.
  update public.quartos
     set status = 'sujo', status_operacional = 'sujo', status_housekeeping = 'sujo',
         status_governanca = 'sujo', control_owner = 'governanca', active_activity = 'checkout_cleaning',
         updated_at = now()
   where id::text = v_room.id::text;

  update public.reservation_room_history
     set actor_user_id = p_actor_user_id
   where id = (select max(id) from public.reservation_room_history where reservation_id = v_reservation.id and event_type = 'checkout');

  return jsonb_build_object('ok', true, 'reservation_id', v_reservation.id, 'room_id', v_room.id, 'status', 'checkout_concluido');
end;
$$;

create or replace function public.reception_room_transfer(
  p_reservation_id text,
  p_to_room_id text,
  p_actor_user_id text default null
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_reservation public.reservas%rowtype;
  v_old_room public.quartos%rowtype;
  v_new_room public.quartos%rowtype;
  v_is_checked_in boolean;
begin
  select * into v_reservation from public.reservas where id::text = p_reservation_id::text for update;
  if not found then raise exception 'Reserva não encontrada.'; end if;
  if v_reservation.status not in ('pendente','confirmada','checkin_realizado') then raise exception 'A reserva não pode ser transferida neste status.'; end if;
  if v_reservation.quarto_id::text = p_to_room_id::text then raise exception 'Selecione outro quarto.'; end if;

  if v_reservation.quarto_id is not null then
    select * into v_old_room from public.quartos where id::text = v_reservation.quarto_id::text for update;
  end if;
  select * into v_new_room from public.quartos where id::text = p_to_room_id::text for update;
  if not found then raise exception 'Quarto de destino não encontrado.'; end if;

  if public.normalize_room_operational_status(coalesce(v_new_room.status_operacional, v_new_room.status)) <> 'disponivel'
     or coalesce(v_new_room.control_owner, 'recepcao') <> 'recepcao' then
    raise exception 'O quarto de destino precisa estar disponível e sob controle da recepção.';
  end if;

  if exists (
    select 1 from public.reservas r
     where r.id::text <> v_reservation.id::text
       and r.quarto_id::text = v_new_room.id::text
       and r.status in ('pendente','confirmada','checkin_realizado')
       and r.checkin < v_reservation.checkout
       and r.checkout > v_reservation.checkin
  ) then raise exception 'O quarto de destino já possui reserva conflitante.'; end if;

  v_is_checked_in := v_reservation.status = 'checkin_realizado';

  update public.reservas set quarto_id = v_new_room.id where id::text = v_reservation.id::text;

  if v_is_checked_in then
    if v_old_room.id is not null then
      update public.quartos
         set status = 'sujo', status_operacional = 'sujo', status_housekeeping = 'sujo',
             status_governanca = 'sujo', control_owner = 'governanca', active_activity = 'recleaning', updated_at = now()
       where id::text = v_old_room.id::text;
    end if;
    update public.quartos
       set status = 'ocupado', status_operacional = 'ocupado', control_owner = 'recepcao', active_activity = null, updated_at = now()
     where id::text = v_new_room.id::text;
  end if;

  update public.reservation_room_history
     set actor_user_id = p_actor_user_id
   where id = (select max(id) from public.reservation_room_history where reservation_id = v_reservation.id and event_type = 'room_transfer');

  return jsonb_build_object(
    'ok', true,
    'reservation_id', v_reservation.id,
    'from_room_id', v_reservation.quarto_id,
    'to_room_id', v_new_room.id,
    'checked_in', v_is_checked_in
  );
end;
$$;

grant execute on function public.refresh_reception_room_guest_binding(text) to anon, authenticated;
grant execute on function public.reception_room_checkin(text, text) to anon, authenticated;
grant execute on function public.reception_room_checkout(text, text) to anon, authenticated;
grant execute on function public.reception_room_transfer(text, text, text) to anon, authenticated;

-- Bring current deterministic reception cards in sync with reservations.
do $$
declare v_room record;
begin
  for v_room in select id from public.quartos loop
    perform public.refresh_reception_room_guest_binding(v_room.id::text);
  end loop;
end;
$$;
