import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ChefHat } from 'lucide-react';
import { atualizarStatusKds, listarKds } from '../../services/pdvService';
import { subscribeToKdsRealtime } from '../../core/realtime';
import type { WorkspaceWidgetRuntimeContext } from '../widgetRuntimeRegistry';

type Status = 'CREATED'|'CONFIRMED'|'PREPARING'|'READY'|'DELIVERING'|'DELIVERED'|'COMPLETED'|'CANCELLED';
type Row = { id:string; order_id:string; status:Status; priority:string; created_at:string; pedido?: { numero?:number; quarto_id?:string|null } | Array<{ numero?:number; quarto_id?:string|null }> | null; item?: { quantidade?:number; produto?:{ nome?:string }|null } | Array<{ quantidade?:number; produto?:{ nome?:string }|null }> | null };
const FLOW: Array<{status:Status; label:string; next?:Status}> = [{status:'CREATED',label:'Novos',next:'CONFIRMED'},{status:'CONFIRMED',label:'Aceitos',next:'PREPARING'},{status:'PREPARING',label:'Em preparo',next:'READY'},{status:'READY',label:'Prontos',next:'DELIVERED'},{status:'DELIVERED',label:'Entregues',next:'COMPLETED'}];
const first = <T,>(value:T|T[]|null|undefined):T|null => Array.isArray(value) ? value[0] || null : value || null;

export const OrdersWidget: React.FC<WorkspaceWidgetRuntimeContext> = ({ widget }) => {
  const sector = typeof widget.filters?.kdsSector === 'string' ? widget.filters.kdsSector : 'COZINHA';
  const [rows,setRows] = useState<Row[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{ try { setRows((await listarKds(sector) || []) as Row[]); setError(null); } catch(e){ setError(e instanceof Error?e.message:'Falha ao carregar pedidos'); } },[sector]);
  useEffect(()=>{ let mounted=true; setLoading(true); void load().finally(()=>{if(mounted)setLoading(false)}); const unsubscribe=subscribeToKdsRealtime(sector,()=>{if(mounted)void load()}); return()=>{mounted=false;unsubscribe()}; },[load,sector]);
  const active=useMemo(()=>rows.filter(row=>!['COMPLETED','CANCELLED'].includes(row.status)),[rows]);
  const advance=async(id:string,next?:Status)=>{ if(!next||widget.permissions?.edit===false)return; try{await atualizarStatusKds(id,next);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar o pedido')} };
  return <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm" data-orders-kds-sector={sector}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-100"><ChefHat className="h-4 w-4"/></span><div><p className="text-[9px] font-black uppercase tracking-wider text-amber-700">Pedidos · {sector}</p><h2 className="text-sm font-black text-slate-900">{widget.title||'Pedidos'}</h2></div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold">{active.length} ativos</span></div>{error&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-[10px] text-red-700">{error}</div>}{loading?<div className="py-8 text-center text-[10px] text-slate-500">Carregando pedidos...</div>:<div className="mt-4 grid gap-3 lg:grid-cols-5">{FLOW.map(column=><section key={column.status} className="rounded-2xl bg-slate-50 p-2"><div className="mb-2 flex justify-between text-[10px] font-black"><span>{column.label}</span><span>{active.filter(row=>row.status===column.status).length}</span></div><div className="space-y-2">{active.filter(row=>row.status===column.status).map(row=>{const pedido=first(row.pedido);const item=first(row.item);return <article key={row.id} className="rounded-xl bg-white p-3 shadow-sm"><strong className="text-[11px]">#{pedido?.numero??row.order_id.slice(0,8)}</strong><div className="mt-1 text-[9px] text-slate-500">{pedido?.quarto_id?`Quarto ${pedido.quarto_id}`:'Balcão'} · {item?.quantidade??0}x {item?.produto?.nome??'Produto'}</div>{column.next&&widget.permissions?.edit!==false&&<button type="button" onClick={()=>void advance(row.id,column.next)} className="mt-2 w-full rounded-lg bg-slate-900 px-2 py-1.5 text-[9px] font-bold text-white">Avançar</button>}</article>})}</div></section>)}</div>}</div>;
};
